#notifications:
#  email:
#    recipients:
#     - etoile-testbuild@gna.org

language: generic

compiler: gcc

os:
  - linux
  - osx

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: cpp
      compiler: clang
      env: TEST_BUILD=gnustep
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.8
          packages:
            - clang-3.8
    - os: osx
      language: objective-c
      compiler: clang
      env: TEST_BUILD=mac
  exclude:
    - compiler: gcc
    - language: generic

script:
  - if [[ $TRAVIS_OS_NAME == 'osx' && $TEST_BUILD == 'mac' ]]; then ./test-macosx.sh; fi
  - if [[ $TRAVIS_OS_NAME == 'linux' && $TEST_BUILD == 'gnustep' ]]; then ./test-linux.sh; fi
