#notifications:
#  email:
#    recipients:
#     - etoile-testbuild@gna.org

language: generic

compiler: gcc

os:
  - linux
  - osx

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: cpp
      compiler: clang
    - os: osx
      language: objective-c
  exclude:
    - compiler: gcc

script:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then ./test-macosx.sh; fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then ./test-linux.sh; fi
